USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS OPENFLOW_ADMIN;
GRANT ROLE OPENFLOW_ADMIN TO USER JHICKOK;

GRANT CREATE OPENFLOW DATA PLANE INTEGRATION ON ACCOUNT TO ROLE OPENFLOW_ADMIN;
GRANT CREATE OPENFLOW RUNTIME INTEGRATION ON ACCOUNT TO ROLE OPENFLOW_ADMIN;
GRANT CREATE COMPUTE POOL ON ACCOUNT TO ROLE OPENFLOW_ADMIN;

ALTER USER JHICKOK SET DEFAULT_ROLE = OPENFLOW_ADMIN;
ALTER USER JHICKOK SET DEFAULT_SECONDARY_ROLES = ('ALL');

CREATE TABLE IF NOT EXISTS EV_INTELLIGENCE.RAW.EV_RAW_OPENFLOW (
  RECORD VARIANT,
  SOURCE_FILE STRING,
  INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);