USE ROLE ACCOUNTADMIN;

GRANT USAGE ON DATABASE EV_INTELLIGENCE TO ROLE EV_MCP_ROLE;
GRANT USAGE ON SCHEMA EV_INTELLIGENCE.AI TO ROLE EV_MCP_ROLE;
GRANT USAGE ON SCHEMA EV_INTELLIGENCE.ANALYTICS TO ROLE EV_MCP_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA EV_INTELLIGENCE.ANALYTICS TO ROLE EV_MCP_ROLE;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA EV_INTELLIGENCE.ANALYTICS TO ROLE EV_MCP_ROLE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA EV_INTELLIGENCE.ANALYTICS TO ROLE EV_MCP_ROLE;

GRANT SELECT ON SEMANTIC VIEW EV_INTELLIGENCE.AI.EV_SEMANTIC TO ROLE EV_MCP_ROLE;
GRANT USAGE ON ALL CORTEX SEARCH SERVICES IN SCHEMA EV_INTELLIGENCE.AI TO ROLE EV_MCP_ROLE;

GRANT USAGE ON WAREHOUSE EV_WH_XS TO ROLE EV_MCP_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE EV_MCP_ROLE;