USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS EV_WH_XS
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS EV_INTELLIGENCE;

CREATE SCHEMA IF NOT EXISTS EV_INTELLIGENCE.RAW;
CREATE SCHEMA IF NOT EXISTS EV_INTELLIGENCE.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS EV_INTELLIGENCE.AI;
CREATE SCHEMA IF NOT EXISTS EV_INTELLIGENCE.ADMIN;