-- Ingest ElectricVehiclePopulationData.json from Azure Blob into EV_INTELLIGENCE.RAW
-- Co-authored with CoCo

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE EV_WH_XS;

CREATE FILE FORMAT IF NOT EXISTS EV_INTELLIGENCE.RAW.JSON_FF
  TYPE = 'JSON'
  STRIP_NULL_VALUES = FALSE;

CREATE STORAGE INTEGRATION IF NOT EXISTS AZINT_EV_DEMO
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'AZURE'
  AZURE_TENANT_ID = '25ecfde7-6b1a-41e9-95ce-9ba633f82519'
  ENABLED = TRUE
  STORAGE_ALLOWED_LOCATIONS = ('azure://stsfazureevdemo.blob.core.windows.net/landing/');

CREATE STAGE IF NOT EXISTS EV_INTELLIGENCE.RAW.STG_AZ_LANDING
  STORAGE_INTEGRATION = AZINT_EV_DEMO
  URL = 'azure://stsfazureevdemo.blob.core.windows.net/landing/'
  FILE_FORMAT = EV_INTELLIGENCE.RAW.JSON_FF;

CREATE TABLE IF NOT EXISTS EV_INTELLIGENCE.RAW.EV_RAW (
  SRC          VARIANT,
  LOAD_TS      TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
  SRC_FILENAME VARCHAR
);

COPY INTO EV_INTELLIGENCE.RAW.EV_RAW (SRC, SRC_FILENAME)
FROM (
  SELECT
    $1,
    METADATA$FILENAME
  FROM @EV_INTELLIGENCE.RAW.STG_AZ_LANDING/ElectricVehiclePopulationData.json
)
ON_ERROR = 'ABORT_STATEMENT';

SELECT ARRAY_SIZE(SRC:data) AS record_count FROM EV_INTELLIGENCE.RAW.EV_RAW;
