CREATE OR REPLACE DYNAMIC TABLE EV_INTELLIGENCE.ANALYTICS.EV_VEHICLES
  TARGET_LAG = '1 minute'
  WAREHOUSE  = EV_WH_XS
  REFRESH_MODE = INCREMENTAL
AS
SELECT
    REC[8]::STRING                          AS VIN_1_10,
    REC[9]::STRING                          AS COUNTY,
    REC[10]::STRING                         AS CITY,
    REC[11]::STRING                         AS STATE,
    REC[12]::STRING                         AS ZIP_CODE,
    TRY_CAST(REC[13]::STRING AS INTEGER)    AS MODEL_YEAR,
    REC[14]::STRING                         AS MAKE,
    REC[15]::STRING                         AS MODEL,
    REC[16]::STRING                         AS EV_TYPE,
    REC[17]::STRING                         AS CAFV_ELIGIBILITY,
    NULLIF(TRY_CAST(REC[18]::STRING AS INTEGER), 0) AS ELECTRIC_RANGE,
    TRY_CAST(REC[20]::STRING AS INTEGER)    AS LEGISLATIVE_DISTRICT,
    REC[21]::STRING                         AS DOL_VEHICLE_ID,
    TRY_TO_GEOGRAPHY(REC[22]::STRING)       AS VEHICLE_LOCATION,
    ST_X(TRY_TO_GEOGRAPHY(REC[22]::STRING))  AS LONGITUDE,
    ST_Y(TRY_TO_GEOGRAPHY(REC[22]::STRING))  AS LATITUDE,
    REC[23]::STRING                         AS ELECTRIC_UTILITY,
    REC[24]::STRING                         AS CENSUS_TRACT_2020,
    (REC[11]::STRING = 'WA')                AS IS_WA_REGISTRATION
FROM EV_INTELLIGENCE.RAW.EV_RECORDS;