USE ROLE ACCOUNTADMIN;
USE WAREHOUSE EV_WH_XS;

CREATE OR REPLACE DYNAMIC TABLE EV_INTELLIGENCE.ANALYTICS.EV_ADOPTION_BY_COUNTY
  TARGET_LAG = '1 hour'
  WAREHOUSE  = EV_WH_XS
AS
SELECT
    COUNTY,
    MODEL_YEAR,
    EV_TYPE,
    COUNT(*) AS VEHICLE_COUNT
FROM EV_INTELLIGENCE.ANALYTICS.EV_VEHICLES
WHERE IS_WA_REGISTRATION = TRUE
GROUP BY COUNTY, MODEL_YEAR, EV_TYPE;

CREATE OR REPLACE DYNAMIC TABLE EV_INTELLIGENCE.ANALYTICS.EV_RANGE_BY_MAKE
  TARGET_LAG = '1 hour'
  WAREHOUSE  = EV_WH_XS
AS
SELECT
    MAKE,
    EV_TYPE,
    AVG(ELECTRIC_RANGE)                 AS AVG_RANGE,
    MEDIAN(ELECTRIC_RANGE)              AS MEDIAN_RANGE,
    COUNT(*)                            AS TOTAL_VEHICLES,
    COUNT(ELECTRIC_RANGE)               AS RESEARCHED_RANGE_COUNT,
    COUNT(*) - COUNT(ELECTRIC_RANGE)    AS UNRESEARCHED_RANGE_COUNT
FROM EV_INTELLIGENCE.ANALYTICS.EV_VEHICLES
GROUP BY MAKE, EV_TYPE;

CREATE OR REPLACE DYNAMIC TABLE EV_INTELLIGENCE.ANALYTICS.EV_DENSITY_BY_ZIP
  TARGET_LAG = '1 hour'
  WAREHOUSE  = EV_WH_XS
AS
SELECT
    ZIP_CODE,
    COUNTY,
    CITY,
    LONGITUDE,
    LATITUDE,
    COUNT(*)                                                        AS VEHICLE_COUNT,
    COUNT_IF(EV_TYPE = 'Battery Electric Vehicle (BEV)')            AS BEV_COUNT,
    COUNT_IF(EV_TYPE = 'Plug-in Hybrid Electric Vehicle (PHEV)')    AS PHEV_COUNT
FROM EV_INTELLIGENCE.ANALYTICS.EV_VEHICLES
WHERE IS_WA_REGISTRATION = TRUE
    AND LATITUDE IS NOT NULL
    AND LONGITUDE IS NOT NULL
GROUP BY ZIP_CODE, COUNTY, CITY, LONGITUDE, LATITUDE;