-- Create Iceberg table from EV_VEHICLES with GEOGRAPHY converted to GeoJSON VARCHAR
-- Co-authored with CoCo
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE EV_WH_XS;

CREATE EXTERNAL VOLUME IF NOT EXISTS EXVOL_EV_ICEBERG
    STORAGE_LOCATIONS = ((
        NAME = 'azure-iceberg'
        STORAGE_PROVIDER = 'AZURE'
        STORAGE_BASE_URL = 'azure://stsfazureevdemo.blob.core.windows.net/iceberg/'
        AZURE_TENANT_ID = '25ecfde7-6b1a-41e9-95ce-9ba633f82519'
    ))
    ALLOW_WRITES = TRUE;

CREATE OR REPLACE ICEBERG TABLE EV_INTELLIGENCE.ANALYTICS.EV_VEHICLES_ICEBERG
  EXTERNAL_VOLUME = 'EXVOL_EV_ICEBERG'
  CATALOG = 'SNOWFLAKE'
  BASE_LOCATION = 'ev_vehicles/'
AS
SELECT
    VIN_1_10,
    COUNTY,
    CITY,
    STATE,
    ZIP_CODE,
    MODEL_YEAR,
    MAKE,
    MODEL,
    EV_TYPE,
    CAFV_ELIGIBILITY,
    ELECTRIC_RANGE,
    LEGISLATIVE_DISTRICT,
    DOL_VEHICLE_ID,
    ST_ASWKT(VEHICLE_LOCATION)::VARCHAR AS VEHICLE_LOCATION,
    ELECTRIC_UTILITY,
    CENSUS_TRACT_2020,
    IS_WA_REGISTRATION
FROM EV_INTELLIGENCE.ANALYTICS.EV_VEHICLES;

SELECT COUNT(*) FROM EV_INTELLIGENCE.ANALYTICS.EV_VEHICLES_ICEBERG;

SELECT SYSTEM$GET_ICEBERG_TABLE_INFORMATION('EV_INTELLIGENCE.ANALYTICS.EV_VEHICLES_ICEBERG');