-- Create Iceberg table if not exists and refresh data via insert overwrite
-- Co-authored with CoCo
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE EV_WH_XS;

CREATE EXTERNAL VOLUME IF NOT EXISTS EXVOL_EV_ICEBERG
    STORAGE_LOCATIONS = ((
        NAME = 'azure-iceberg'
        STORAGE_PROVIDER = 'AZURE'
        STORAGE_BASE_URL = 'azure://stsfazureevdemo.blob.core.windows.net/iceberg/'
        AZURE_TENANT_ID = '25ecfde7-6b1a-41e9-95ce-9ba633f82519'
    ))
    ALLOW_WRITES = TRUE;

CREATE ICEBERG TABLE IF NOT EXISTS EV_INTELLIGENCE.ANALYTICS.EV_VEHICLES_ICEBERG (
    VIN_1_10 STRING,
    COUNTY STRING,
    CITY STRING,
    STATE STRING,
    ZIP_CODE STRING,
    MODEL_YEAR NUMBER(38,0),
    MAKE STRING,
    MODEL STRING,
    EV_TYPE STRING,
    CAFV_ELIGIBILITY STRING,
    ELECTRIC_RANGE NUMBER(38,0),
    LEGISLATIVE_DISTRICT STRING,
    DOL_VEHICLE_ID NUMBER(38,0),
    LONGITUDE FLOAT,
    LATITUDE FLOAT,
    ELECTRIC_UTILITY STRING,
    CENSUS_TRACT_2020 NUMBER(38,0),
    IS_WA_REGISTRATION BOOLEAN
)
  EXTERNAL_VOLUME = 'EXVOL_EV_ICEBERG'
  CATALOG = 'SNOWFLAKE'
  BASE_LOCATION = 'ev_vehicles/';

INSERT OVERWRITE INTO EV_INTELLIGENCE.ANALYTICS.EV_VEHICLES_ICEBERG
SELECT
    VIN_1_10,
    COUNTY,
    CITY,
    STATE,
    ZIP_CODE,
    MODEL_YEAR,
    MAKE,
    MODEL,
    EV_TYPE,
    CAFV_ELIGIBILITY,
    ELECTRIC_RANGE,
    LEGISLATIVE_DISTRICT,
    TRY_CAST(DOL_VEHICLE_ID AS NUMBER(38,0)) AS DOL_VEHICLE_ID,
    LONGITUDE,
    LATITUDE,
    ELECTRIC_UTILITY,
    TRY_CAST(CENSUS_TRACT_2020 AS NUMBER(38,0)) AS CENSUS_TRACT_2020,
    IS_WA_REGISTRATION
FROM EV_INTELLIGENCE.ANALYTICS.EV_VEHICLES;

SELECT COUNT(*) FROM EV_INTELLIGENCE.ANALYTICS.EV_VEHICLES_ICEBERG;

SELECT SYSTEM$GET_ICEBERG_TABLE_INFORMATION('EV_INTELLIGENCE.ANALYTICS.EV_VEHICLES_ICEBERG');