-- Governance: least-privilege role, VIN masking policy, and secure sharing view
-- Co-authored with CoCo

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE EV_WH_XS;

-----------------------------------------------------------------------
-- 1. Least-privilege role: EV_MCP_ROLE (read-only on ANALYTICS schema)
-----------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS EV_MCP_ROLE;
 
GRANT USAGE ON WAREHOUSE EV_WH_XS TO ROLE EV_MCP_ROLE;
GRANT USAGE ON DATABASE EV_INTELLIGENCE TO ROLE EV_MCP_ROLE;
GRANT USAGE ON SCHEMA EV_INTELLIGENCE.ANALYTICS TO ROLE EV_MCP_ROLE;
GRANT USAGE ON SCHEMA EV_INTELLIGENCE.AI TO ROLE EV_MCP_ROLE;
 
GRANT SELECT ON ALL TABLES IN SCHEMA EV_INTELLIGENCE.ANALYTICS TO ROLE EV_MCP_ROLE;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA EV_INTELLIGENCE.ANALYTICS TO ROLE EV_MCP_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA EV_INTELLIGENCE.ANALYTICS TO ROLE EV_MCP_ROLE;
 
GRANT SELECT ON FUTURE TABLES IN SCHEMA EV_INTELLIGENCE.ANALYTICS TO ROLE EV_MCP_ROLE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA EV_INTELLIGENCE.ANALYTICS TO ROLE EV_MCP_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA EV_INTELLIGENCE.ANALYTICS TO ROLE EV_MCP_ROLE;
 
GRANT SELECT ON ALL SEMANTIC VIEWS IN SCHEMA EV_INTELLIGENCE.AI TO ROLE EV_MCP_ROLE;
GRANT SELECT ON FUTURE SEMANTIC VIEWS IN SCHEMA EV_INTELLIGENCE.AI TO ROLE EV_MCP_ROLE;
 
GRANT USAGE ON ALL CORTEX SEARCH SERVICES IN SCHEMA EV_INTELLIGENCE.AI TO ROLE EV_MCP_ROLE;
GRANT USAGE ON FUTURE CORTEX SEARCH SERVICES IN SCHEMA EV_INTELLIGENCE.AI TO ROLE EV_MCP_ROLE;
 
GRANT ROLE EV_MCP_ROLE TO ROLE SYSADMIN;
 
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE EV_MCP_ROLE;

GRANT CREATE STREAMLIT ON SCHEMA EV_INTELLIGENCE.AI TO ROLE EV_MCP_ROLE;
GRANT CREATE STAGE ON SCHEMA EV_INTELLIGENCE.AI TO ROLE EV_MCP_ROLE;
GRANT ROLE EV_MCP_ROLE TO USER JHICKOK;

-----------------------------------------------------------------------
-- 2. Masking policy: only ACCOUNTADMIN sees full VIN
-----------------------------------------------------------------------
CREATE OR REPLACE MASKING POLICY EV_INTELLIGENCE.ANALYTICS.VIN_MASK
  AS (val STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() = 'ACCOUNTADMIN' THEN val
    ELSE CONCAT('***', RIGHT(val, 4))
  END;

ALTER DYNAMIC TABLE EV_INTELLIGENCE.ANALYTICS.EV_VEHICLES
  MODIFY COLUMN VIN_1_10 SET MASKING POLICY EV_INTELLIGENCE.ANALYTICS.VIN_MASK;

-----------------------------------------------------------------------
-- 3. Secure view for sharing to a reader account
-----------------------------------------------------------------------
CREATE OR REPLACE SECURE VIEW EV_INTELLIGENCE.ANALYTICS.EV_ADOPTION_BY_COUNTY_SHARED
AS
SELECT
    COUNTY,
    MODEL_YEAR,
    EV_TYPE,
    VEHICLE_COUNT
FROM EV_INTELLIGENCE.ANALYTICS.EV_ADOPTION_BY_COUNTY;

-- Create a share and grant the secure view to it
CREATE SHARE IF NOT EXISTS EV_ADOPTION_SHARE;
GRANT USAGE ON DATABASE EV_INTELLIGENCE TO SHARE EV_ADOPTION_SHARE;
GRANT USAGE ON SCHEMA EV_INTELLIGENCE.ANALYTICS TO SHARE EV_ADOPTION_SHARE;
GRANT SELECT ON VIEW EV_INTELLIGENCE.ANALYTICS.EV_ADOPTION_BY_COUNTY_SHARED TO SHARE EV_ADOPTION_SHARE;
