USE ROLE ACCOUNTADMIN;
USE WAREHOUSE EV_WH_XS;

CREATE STAGE IF NOT EXISTS EV_INTELLIGENCE.RAW.MANUALS
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE STAGE IF NOT EXISTS EV_INTELLIGENCE.RAW.PHOTOS
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

GRANT READ ON STAGE EV_INTELLIGENCE.RAW.MANUALS TO ROLE EV_MCP_ROLE;
GRANT READ ON STAGE EV_INTELLIGENCE.RAW.PHOTOS TO ROLE EV_MCP_ROLE;
GRANT USAGE ON SCHEMA EV_INTELLIGENCE.RAW TO ROLE EV_MCP_ROLE;

CREATE OR REPLACE TABLE EV_INTELLIGENCE.RAW.MANUAL_DOCS AS
SELECT
    RELATIVE_PATH AS SOURCE_FILE,
    SPLIT_PART(RELATIVE_PATH, '_', 1) AS MAKE_SLUG,
    REGEXP_REPLACE(
        SNOWFLAKE.CORTEX.PARSE_DOCUMENT(
            @EV_INTELLIGENCE.RAW.MANUALS,
            RELATIVE_PATH,
            {'mode': 'LAYOUT'}
        ):content::STRING,
        '!\\[img-[0-9]+\\.[a-z]+\\]\\([^)]*\\)', ''
    ) AS DOC_TEXT
FROM DIRECTORY(@EV_INTELLIGENCE.RAW.MANUALS);

CREATE OR REPLACE TABLE EV_INTELLIGENCE.RAW.MANUAL_CHUNKS AS
SELECT
    d.SOURCE_FILE,
    d.MAKE_SLUG,
    c.INDEX AS CHUNK_INDEX,
    c.VALUE::STRING AS CHUNK_TEXT
FROM EV_INTELLIGENCE.RAW.MANUAL_DOCS d,
LATERAL FLATTEN(
    SNOWFLAKE.CORTEX.SPLIT_TEXT_RECURSIVE_CHARACTER(
        d.DOC_TEXT,
        'markdown',
        1500,
        300
    )
) c;

CREATE OR REPLACE CORTEX SEARCH SERVICE EV_INTELLIGENCE.AI.EV_MANUAL_SEARCH
    ON CHUNK_TEXT
    ATTRIBUTES SOURCE_FILE, MAKE_SLUG
    WAREHOUSE = EV_WH_XS
    TARGET_LAG = '1 hour'
AS
SELECT
    CHUNK_TEXT,
    SOURCE_FILE,
    MAKE_SLUG,
    CHUNK_INDEX
FROM EV_INTELLIGENCE.RAW.MANUAL_CHUNKS;

CREATE OR REPLACE TABLE EV_INTELLIGENCE.ANALYTICS.VEHICLE_PHOTO_CATALOG (
    MAKE STRING,
    MODEL STRING,
    RELATIVE_PATH STRING,
    ATTRIBUTION STRING,
    LICENSE STRING,
    SOURCE_URL STRING
);

INSERT INTO EV_INTELLIGENCE.ANALYTICS.VEHICLE_PHOTO_CATALOG
    (MAKE, MODEL, RELATIVE_PATH)
VALUES
    ('TESLA', 'MODEL 3', 'tesla_model3.jpeg'),
    ('TESLA', 'MODEL Y', 'tesla_modely.jpeg'),
    ('NISSAN', 'LEAF', 'nissan_leaf.jpeg'),
    ('CHEVROLET', 'BOLT EV', 'chevrolet_bolt.jpeg');

CREATE OR REPLACE FUNCTION EV_INTELLIGENCE.AI.GET_VEHICLE_PHOTO(MAKE_IN STRING, MODEL_IN STRING)
RETURNS TABLE (MAKE STRING, MODEL STRING, PHOTO_URL STRING, ATTRIBUTION STRING, LICENSE STRING)
AS
$$
SELECT
    MAKE,
    MODEL,
    GET_PRESIGNED_URL(@EV_INTELLIGENCE.RAW.PHOTOS, RELATIVE_PATH, 3600) AS PHOTO_URL,
    ATTRIBUTION,
    LICENSE
FROM EV_INTELLIGENCE.ANALYTICS.VEHICLE_PHOTO_CATALOG
WHERE UPPER(MAKE) = UPPER(MAKE_IN)
    AND UPPER(MODEL) = UPPER(MODEL_IN)
$$;

GRANT USAGE ON FUNCTION EV_INTELLIGENCE.AI.GET_VEHICLE_PHOTO(STRING, STRING) TO ROLE EV_MCP_ROLE;