-- LONG RUNNING: PARSE_DOCUMENT in LAYOUT mode is bound by the document AI service,
-- not by warehouse size. A first run over eight manuals takes well over an hour.
-- Subsequent runs parse only files not already in MANUAL_DOCS.

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE EV_WH_XS;

CREATE STAGE IF NOT EXISTS EV_INTELLIGENCE.RAW.MANUALS
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE STAGE IF NOT EXISTS EV_INTELLIGENCE.RAW.PHOTOS
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

ALTER STAGE EV_INTELLIGENCE.RAW.MANUALS REFRESH;
ALTER STAGE EV_INTELLIGENCE.RAW.PHOTOS REFRESH;

GRANT READ ON STAGE EV_INTELLIGENCE.RAW.MANUALS TO ROLE EV_MCP_ROLE;
GRANT READ ON STAGE EV_INTELLIGENCE.RAW.PHOTOS TO ROLE EV_MCP_ROLE;
GRANT USAGE ON SCHEMA EV_INTELLIGENCE.RAW TO ROLE EV_MCP_ROLE;

CREATE TABLE IF NOT EXISTS EV_INTELLIGENCE.RAW.MANUAL_DOCS (
    SOURCE_FILE STRING,
    MAKE_SLUG STRING,
    DOC_TEXT STRING
);

INSERT INTO EV_INTELLIGENCE.RAW.MANUAL_DOCS (SOURCE_FILE, MAKE_SLUG, DOC_TEXT)
SELECT
    RELATIVE_PATH AS SOURCE_FILE,
    SPLIT_PART(RELATIVE_PATH, '_', 1) AS MAKE_SLUG,
    REGEXP_REPLACE(
        SNOWFLAKE.CORTEX.PARSE_DOCUMENT(
            @EV_INTELLIGENCE.RAW.MANUALS,
            RELATIVE_PATH,
            {'mode': 'LAYOUT'}
        ):content::STRING,
        '!\\[img-[0-9]+\\.[a-z]+\\]\\([^)]*\\)', ''
    ) AS DOC_TEXT
FROM DIRECTORY(@EV_INTELLIGENCE.RAW.MANUALS)
WHERE RELATIVE_PATH NOT IN (
    SELECT SOURCE_FILE FROM EV_INTELLIGENCE.RAW.MANUAL_DOCS
);

CREATE OR REPLACE TABLE EV_INTELLIGENCE.RAW.MANUAL_CHUNKS AS
SELECT
    d.SOURCE_FILE,
    d.MAKE_SLUG,
    c.INDEX AS CHUNK_INDEX,
    c.VALUE::STRING AS CHUNK_TEXT
FROM EV_INTELLIGENCE.RAW.MANUAL_DOCS d,
LATERAL FLATTEN(
    SNOWFLAKE.CORTEX.SPLIT_TEXT_RECURSIVE_CHARACTER(
        d.DOC_TEXT,
        'markdown',
        1500,
        300
    )
) c;

CREATE OR REPLACE CORTEX SEARCH SERVICE EV_INTELLIGENCE.AI.EV_MANUAL_SEARCH
    ON CHUNK_TEXT
    ATTRIBUTES SOURCE_FILE, MAKE_SLUG
    WAREHOUSE = EV_WH_XS
    TARGET_LAG = '1 hour'
AS
SELECT
    CHUNK_TEXT,
    SOURCE_FILE,
    MAKE_SLUG,
    CHUNK_INDEX
FROM EV_INTELLIGENCE.RAW.MANUAL_CHUNKS;

CREATE TABLE IF NOT EXISTS EV_INTELLIGENCE.ANALYTICS.VEHICLE_PHOTO_CATALOG (
    MAKE STRING,
    MODEL STRING,
    RELATIVE_PATH STRING,
    ATTRIBUTION STRING,
    LICENSE STRING,
    SOURCE_URL STRING
);

MERGE INTO EV_INTELLIGENCE.ANALYTICS.VEHICLE_PHOTO_CATALOG t
USING (
    SELECT * FROM VALUES
        ('TESLA', 'MODEL 3', 'tesla_model3.jpeg', 'Unknown', 'CC BY-SA 4.0', NULL),
        ('TESLA', 'MODEL Y', 'tesla_modely.jpeg', 'Unknown', 'CC BY-SA 4.0', NULL),
        ('NISSAN', 'LEAF', 'nissan_leaf.jpeg', 'Unknown', 'CC BY-SA 4.0', NULL),
        ('CHEVROLET', 'BOLT EV', 'chevrolet_bolt.jpeg', 'Unknown', 'CC BY-SA 4.0', NULL)
    AS v(MAKE, MODEL, RELATIVE_PATH, ATTRIBUTION, LICENSE, SOURCE_URL)
) s
ON t.MAKE = s.MAKE AND t.MODEL = s.MODEL
WHEN MATCHED THEN UPDATE SET
    t.RELATIVE_PATH = s.RELATIVE_PATH,
    t.ATTRIBUTION = s.ATTRIBUTION,
    t.LICENSE = s.LICENSE,
    t.SOURCE_URL = s.SOURCE_URL
WHEN NOT MATCHED THEN INSERT
    (MAKE, MODEL, RELATIVE_PATH, ATTRIBUTION, LICENSE, SOURCE_URL)
    VALUES (s.MAKE, s.MODEL, s.RELATIVE_PATH, s.ATTRIBUTION, s.LICENSE, s.SOURCE_URL);

CREATE OR REPLACE FUNCTION EV_INTELLIGENCE.AI.GET_VEHICLE_PHOTO(MAKE_IN STRING, MODEL_IN STRING)
RETURNS TABLE (MAKE STRING, MODEL STRING, PHOTO_URL STRING, ATTRIBUTION STRING, LICENSE STRING)
AS
$$
SELECT
    MAKE,
    MODEL,
    GET_PRESIGNED_URL(@EV_INTELLIGENCE.RAW.PHOTOS, RELATIVE_PATH, 3600) AS PHOTO_URL,
    ATTRIBUTION,
    LICENSE
FROM EV_INTELLIGENCE.ANALYTICS.VEHICLE_PHOTO_CATALOG
WHERE UPPER(MAKE) = UPPER(MAKE_IN)
    AND UPPER(MODEL) = UPPER(MODEL_IN)
$$;

GRANT USAGE ON FUNCTION EV_INTELLIGENCE.AI.GET_VEHICLE_PHOTO(STRING, STRING) TO ROLE EV_MCP_ROLE;