USE ROLE ACCOUNTADMIN;


CREATE OR REPLACE MCP SERVER EV_INTELLIGENCE.AI.EV_MCP
FROM SPECIFICATION
$$
tools:
  - name: ev_agent
    identifier: EV_INTELLIGENCE.AI.EV_AGENT
    type: CORTEX_AGENT_RUN
    description: "Answers questions about Washington State electric vehicle registrations, EV owner's manuals, and vehicle photos."
$$;

GRANT USAGE ON MCP SERVER EV_INTELLIGENCE.AI.EV_MCP TO ROLE EV_MCP_ROLE;

CREATE SECURITY INTEGRATION IF NOT EXISTS EV_MCP_OAUTH
  TYPE = OAUTH
  OAUTH_CLIENT = CUSTOM
  OAUTH_CLIENT_TYPE = 'CONFIDENTIAL'
  OAUTH_REDIRECT_URI = 'https://localhost'
  OAUTH_ISSUE_REFRESH_TOKENS = TRUE
  OAUTH_REFRESH_TOKEN_VALIDITY = 86400
  ENABLED = TRUE;