USE ROLE ACCOUNTADMIN;

CREATE NOTIFICATION INTEGRATION IF NOT EXISTS AZNOTIF_EV_DEMO
  ENABLED = TRUE
  TYPE = QUEUE
  NOTIFICATION_PROVIDER = AZURE_STORAGE_QUEUE
  AZURE_STORAGE_QUEUE_PRIMARY_URI = 'https://stsfazureevdemo.queue.core.windows.net/snowpipe-queue'
  AZURE_TENANT_ID = '25ecfde7-6b1a-41e9-95ce-9ba633f82519';

CREATE STAGE IF NOT EXISTS EV_INTELLIGENCE.RAW.STG_AZ_INCOMING
  URL = 'azure://stsfazureevdemo.blob.core.windows.net/landing/incoming/'
  STORAGE_INTEGRATION = AZINT_EV_DEMO
  FILE_FORMAT = EV_INTELLIGENCE.RAW.JSON_FF;

CREATE PIPE IF NOT EXISTS EV_INTELLIGENCE.RAW.EV_PIPE
  AUTO_INGEST = TRUE
  INTEGRATION = 'AZNOTIF_EV_DEMO'
AS
COPY INTO EV_INTELLIGENCE.RAW.EV_RAW (SRC, LOAD_TS, SRC_FILENAME)
FROM (
  SELECT $1, CURRENT_TIMESTAMP(), METADATA$FILENAME
  FROM @EV_INTELLIGENCE.RAW.STG_AZ_INCOMING
);

CREATE TABLE IF NOT EXISTS EV_INTELLIGENCE.RAW.EV_RECORDS (
  DOL_VEHICLE_ID STRING,
  REC VARIANT,
  LOAD_TS TIMESTAMP_NTZ,
  SRC_FILENAME STRING
);

CREATE STREAM IF NOT EXISTS EV_INTELLIGENCE.RAW.EV_RAW_STREAM
  ON TABLE EV_INTELLIGENCE.RAW.EV_RAW;

CREATE OR REPLACE TASK EV_INTELLIGENCE.RAW.T_EXPLODE_EV
  USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
  SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('EV_INTELLIGENCE.RAW.EV_RAW_STREAM')
AS
MERGE INTO EV_INTELLIGENCE.RAW.EV_RECORDS t
USING (
  SELECT
    r.value[21]::STRING AS DOL_VEHICLE_ID,
    r.value              AS REC,
    s.LOAD_TS,
    s.SRC_FILENAME
  FROM EV_INTELLIGENCE.RAW.EV_RAW_STREAM s,
       LATERAL FLATTEN(input => s.SRC:data) r
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY r.value[21]::STRING ORDER BY s.LOAD_TS DESC
  ) = 1
) src
ON t.DOL_VEHICLE_ID = src.DOL_VEHICLE_ID
WHEN MATCHED THEN UPDATE SET
  t.REC = src.REC, t.LOAD_TS = src.LOAD_TS, t.SRC_FILENAME = src.SRC_FILENAME
WHEN NOT MATCHED THEN INSERT
  (DOL_VEHICLE_ID, REC, LOAD_TS, SRC_FILENAME)
  VALUES (src.DOL_VEHICLE_ID, src.REC, src.LOAD_TS, src.SRC_FILENAME);

CREATE OR REPLACE TASK EV_INTELLIGENCE.RAW.T_REFRESH_ICEBERG
  USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
  AFTER EV_INTELLIGENCE.RAW.T_EXPLODE_EV
AS
INSERT OVERWRITE INTO EV_INTELLIGENCE.ANALYTICS.EV_VEHICLES_ICEBERG
SELECT
    VIN_1_10,
    COUNTY,
    CITY,
    STATE,
    ZIP_CODE,
    MODEL_YEAR,
    MAKE,
    MODEL,
    EV_TYPE,
    CAFV_ELIGIBILITY,
    ELECTRIC_RANGE,
    LEGISLATIVE_DISTRICT,
    TRY_CAST(DOL_VEHICLE_ID AS NUMBER(38,0)) AS DOL_VEHICLE_ID,
    LONGITUDE,
    LATITUDE,
    ELECTRIC_UTILITY,
    TRY_CAST(CENSUS_TRACT_2020 AS NUMBER(38,0)) AS CENSUS_TRACT_2020,
    IS_WA_REGISTRATION
FROM EV_INTELLIGENCE.ANALYTICS.EV_VEHICLES;

ALTER TASK EV_INTELLIGENCE.RAW.T_EXPLODE_EV SUSPEND;
ALTER TASK EV_INTELLIGENCE.RAW.T_REFRESH_ICEBERG RESUME;
ALTER TASK EV_INTELLIGENCE.RAW.T_EXPLODE_EV RESUME;